
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rigcare_development

test:
  <<: *default
  database: rigcare_test

production:
  <<: *default
  database: myapp
  username: deploy
<<<<<<< HEAD
  password: Far21zXc31r
=======
  


>>>>>>> 44fa57812e1e996cb96b16957cfe366517146507
